	if(!global.hasOwnProperty("db")){
	var mongoose =require("mongoose");
	mongoose.connect("mongodb://localhost/nombrebd");
	
	global.db={
		mongoose:mongoose,
		Usuarios:mongoose.model("Usuarios",{
			Nombre:String,
			Contraseña:String,
			Clase:String,
			Email:String,
			Votos:{type:Number,default:0},
			Capital:{type:String,default:100},
			Favoritos:[],
			Votados:[],
			Admin:{type:Boolean,default:false}
		}),
		Productos:mongoose.model("Productos",{
			Nombre:String,
			Categoria:String,
			Descripcion:String,
			Precio:String,
			Clase:String,
			Imagenes:[],
			Fecha:String,
			Nombre_Usuario:String,
			Clase_Usuario:String,
			Ubicacion:String,
			Clase_Comprador:String,
			Votos:String,
			Estado:{type:Boolean,default:true},
		}),
		Compras:mongoose.model("Compras",{
			Nombre:String,
			Categoria:String,
			Descripcion:String,
			Precio:String,
			Clase:String,
			Imagenes:[],
			Fecha:String,
			Vendedor_Clase:String,
			Comprador_Clase:String
		}),
		Ventas:mongoose.model("Ventas",{
			Nombre:String,
			Categoria:String,
			Descripcion:String,
			Precio:String,
			Clase:String,
			Imagenes:[],
			Fecha:String,
			Vendedor_Clase:String
		}),
		Claves:mongoose.model("Claves",{
			Clave:String,
			Usada:{type:Boolean,default:false},
			Valor:Number
		}),
		Contactanos:mongoose.model("Contactanos",{
			Problema:String,
			Categoria:String,
			Email:String,
		}),
	}
}
module.exports=global.db;